export type AppData = {
  id: string;
  key: string;
  userId: string;
  userToken: string;
};

export const appDataJwt =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEzMjIyODEiLCJrZXkiOiI4aG4yNTJlZWdxcTkiLCJ1c2VySWQiOiI2Njg1YWVkMjVlOTFhNTFjMDM2MTI1MWYiLCJ1c2VyVG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKMWMyVnlYMmxrSWpvaU5qWTROV0ZsWkRJMVpUa3hZVFV4WXpBek5qRXlOVEZtSW4wLjRtcnlreTdabExjNTVOWE8xVEpwZ2dsUGNFaU9iUmNOUXg1MVJ5WXdic0kifQ.lvfRx-kLVvoYhYSn_p6avhOXO1eH3ZuJnqzRtrdSw7Y";
