export type User = {
  _id: string;
  bio?: string;
  chatToken: string;
  email: string;
  feedToken: string;
  followers: { [userId: string]: string };
  following: { [userId: string]: string };
  name: string;
  profileImage: string;
  coverImage?: string;
  username: string;
  verified?: boolean;
  isAdmin?: boolean;
  invalid?: boolean;
  youtube?: string;
  tiktok?: string;
  instagram?: string;
  customLink?: string;
  followersId?: Set<string>;
  followingId?: Set<string>;
};
